'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PROJECT.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0979c136_c2ac_4649_a3c4_ad4f04924e09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0979c136-c2ac-4649-a3c4-ad4f04924e09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _17a30e4a_d005_45ef_b255_300cacd3e792() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("17a30e4a-d005-45ef-b255-300cacd3e792", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _19f5200c_5223_4450_bd0d_eb4584c59c3e() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("19f5200c-5223-4450-bd0d-eb4584c59c3e", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _338289bb_f3c1_4e48_9978_7186e7839849() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("338289bb-f3c1-4e48-9978-7186e7839849", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3ea8f8f8_394c_48d2_904c_486b33d61d55() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3ea8f8f8-394c-48d2-904c-486b33d61d55", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5dd09db7_dca1_4225_8646_41448c5fd1a9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5dd09db7-dca1-4225-8646-41448c5fd1a9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _88bbc1c6_72bb_4f6d_b22d_9509ca056557() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("88bbc1c6-72bb-4f6d-b22d-9509ca056557", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8bebca42_8244_404b_ad6a_56ee70780f70() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8bebca42-8244-404b-ad6a-56ee70780f70", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9047f547_1ad9_4660_aa78_4da692199680() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9047f547-1ad9-4660-aa78-4da692199680", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9d87594c_d5a7_40d3_b3b8_0059b0fbd1f5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9d87594c-d5a7-40d3-b3b8-0059b0fbd1f5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9d87594c_d5a7_40d3_b3b8_0059b0fbd1f51() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9d87594c-d5a7-40d3-b3b8-0059b0fbd1f51", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9e4a6b02_0679_4b6f_bb4f_b0421886e560() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9e4a6b02-0679-4b6f-bb4f-b0421886e560", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9fa42090_b4f3_4922_8c80_9ccf71c3542f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9fa42090-b4f3-4922-8c80-9ccf71c3542f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9fa42090_b4f3_4922_8c80_9ccf71c3542f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9fa42090-b4f3-4922-8c80-9ccf71c3542f1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _9fa42090_b4f3_4922_8c80_9ccf71c3542f2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9fa42090-b4f3-4922-8c80-9ccf71c3542f2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ab0b2367_ed20_47f2_9529_d628c66dac0b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ab0b2367-ed20-47f2-9529-d628c66dac0b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d8e48688_c935_46d8_804d_fbc8c3e46e44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d8e48688-c935-46d8-804d-fbc8c3e46e44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property e623a417_5e17_4c84_94c7_761f528b2578() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("e623a417-5e17-4c84-94c7-761f528b2578", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f6e410ba_5f6f_4736_93fe_e324afe4efbe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6e410ba-5f6f-4736-93fe-e324afe4efbe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f6e410ba_5f6f_4736_93fe_e324afe4efbe1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f6e410ba-5f6f-4736-93fe-e324afe4efbe1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property istockphoto_1445857687_612x612() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("istockphoto-1445857687-612x612", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
